### ISSUE TITLE
The word "ocelot" breaks macroetym?

### ISSUE THREAD

**Issue by cvd6262** [JonathanReeve/macro-etym#23]
Awesome tool. I'm having fun plugging in some corpora I have from other projects. I had two files that kept throwing errors, and, by splitting those files, I was able to locate the word causing the problems. It's "ocelot". Here's how to replicate it:

This works:
cvd6262$
 echo "tiger bear" > test.txt
cvd6262$ macroetym test.txt 
              test.txt
Austronesian       0.0
Balto-Slavic       0.0
Celtic             0.0
Germanic         100.0
Hellenic           0.0
Indo-Iranian       0.0
Japonic            0.0
Latinate           0.0
Semitic            0.0
Turkic             0.0
Uralic             0.0`

This doesn't work:
cvd6262$ echo "tiger ocelot" > test.txt
cvd6262$ macroetym test.txt 
Traceback (most recent call last):
  File "/usr/local/bin/macroetym", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/macroetym/main.py", line 404, in cli
    cumulativeAllStats[filename] = t.prettyStats
  File "/usr/local/lib/python3.5/site-packages/macroetym/main.py", line 336, in prettyStats
    return self.getStats(pretty=True)
  File "/usr/local/lib/python3.5/site-packages/macroetym/main.py", line 289, in getStats
    prettyLang = languages.get(iso639_3_code=lang).name
  File "/usr/local/lib/python3.5/site-packages/pycountry/db.py", line 21, in load_if_needed
    return f(self, *args, **kw)
  File "/usr/local/lib/python3.5/site-packages/pycountry/db.py", line 128, in get
    return self.indices[field][value]
KeyError: 'nah'
cvd6262$

**Comment by JonathanReeve** [comment]
Thanks for the bug report! It looks like "ocelot" has the etymology: `nah: ocelotl`, and strangely, the `pycountry` module I'm using to translate language codes into language names doesn't have `nah` (Nahuatl) in its dictionary, so it's throwing an error. I'll have to wrap this line in a try/except, and then submit a bug report to pycountry to add this language. 

You might be able to work around this issue temporarily by turning off pretty language formatting (it'll just give you the codes then) in line 336, by changing True to False.

**Comment by cvd6262** [comment]
Awesome. Thanks.

**Comment by JonathanReeve** [comment]
It should be working now. The patched version isn't up on pypi yet, but you can download it here, and it should work: 

```
$ echo "ocelot" > test.txt
$ python main.py test.txt 
              test.txt
Austronesian       0.0
Balto-Slavic       0.0
Celtic             0.0
Germanic           0.0
Hellenic           0.0
Indo-Iranian       0.0
Japonic            0.0
Latinate           0.0
Other            100.0
Semitic            0.0
Turkic             0.0
Uralic             0.0
```

It's not great with minority language families at the moment.
